language: ruby
bundler_args: --without development production
env:
  - APP_BOLAO_SECRET_TOKEN=4332f52629f19ce91a0f5d7729deede34ed4ae5bb537eeb21720dab8f929748d24ed6c5a353668306376fc41d1cdfbfd6b8cdd5e4b11c5e56deb2884c19d3291
rvm:
  - 2.1.2
addons:
   code_climate:
     repo_token: 44daf63b2429a65c10170d2a1abcae6812d1648c075cdb3dcde54d01a27e1c54 
before_script:
  - cp config/database.travis.yml config/database.yml
  - mysql -e 'create database bolao_test;'
  - bundle exec rake db:test:load
